### ISSUE TITLE
SMuFL fonts section out of date

### ISSUE THREAD

**Issue by bbloomf** [rism-digital/verovio-reference-book#37]
The [`Music symbols in text` section](https://book.verovio.org/advanced-topics/smufl.html#music-symbols-in-text) says that the VerovioText font is used for music symbols displayed within the text, but I believe that as of Verovoi version 3.12 this is no longer the case.

Also, I think the SVGs in that section do not have the Leipzig font included in them, and so the elements that reference it display as rectangles:
![image](https://book.verovio.org/images/examples/04-advanced-topics/03-smufl/lyric-01.svg)
![image](https://book.verovio.org/images/examples/04-advanced-topics/03-smufl/tempo-01.svg)
![image](https://book.verovio.org/images/examples/04-advanced-topics/03-smufl/dynam-01.svg)

**Comment by lpugin** [comment]
The issue with the font missing is fixed.
