### ISSUE TITLE
Improve book structure

### ISSUE THREAD

**Issue by lpugin** [rism-digital/verovio-reference-book#6]
One thing that is currently not optimal with the book structure is that `h3` (###) headings in chapter top documents are not listed in the table of content (sidebar). They are when used in a section.

One option is to move these chapter top documents within the chapter directorey. So instead of having
```
01-introduction
 |-01-about.md
 |-02-licensing.md
01-introduction.md
```
We could do
```
01-introduction
 |-00-index.md
 |-01-about.md
 |-02-licensing.md
```
Clicking on introduction would show the content of `00-index.md` and subsections would be listed underneath. This would also facilitate the navigation in the book files. However, it would work only - as things stand - if `00-index.md` has a title to show as section in the navigation. For most chapter, it would be 'Introduction'. Since we don't want 
```
Introduction
  Introduction
 ```
for the first chapter, we could rename one of the two "About this book". Any thoughts?

**Comment by ahankinson** [comment]
I like the idea of all content being included in the folder, rather than a top-level file and then the rest in the folder.

**Comment by lpugin** [comment]
Chapter top documents are now `00-index.md` files with an additional `chapter-title` key.
