### ISSUE TITLE
Some options not appearing

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio-reference-book#8]
In the toolkit options page (https://book.verovio.org/toolkit-reference/toolkit-options.html) some options, like 'scale', do not appear.

**Comment by lpugin** [comment]
Yes, some options are not set through `Toolkit::SetOptions` but through their individual methods (e.g,. `Toolkit::SetScale`). Basically these ones https://github.com/rism-digital/verovio.org/blob/gh-pages/_includes/cli.txt#L7-L21. This is why they do not appear in the output of `Toolkit::GetAvailableOptions`.

I thought about adding them to the output of `Toolkit::GetAvailableOptions`, but we need to make sure it is clear they cannot not be changed via `SetOptions`. 

Alternatively we could deprecate them. In any case, some a are specific to the command-line (`--page`, or `--all-pages`) and will have to remain.

**Comment by lpugin** [comment]
This is what we have now
https://book.verovio.org/toolkit-reference/toolkit-options.html
I think the main point will be to add links to sections for the options that have no corresponding JSON key to be used with `SetOptions`.
